width = 12
height = 7

[[hexes]]
rails = [
    {edges = [5], location = {values = [40, 50, 60, 80], stations = ["P&LE"], name = "Pittsburgh"}}
]
color = "Red"
x = 0
y = 1

[[hexes]]
rails = [
    {edges = [4], location = {values = [40, 60, 80, 100], name = "Ohio"}},
    {edges = [5], location = {values = [40, 60, 80, 100], name = "Ohio"}}
]
color = "Red"
x = 0
y = 3

[[hexes]]
rails = [
    {edges = [4], location = {values = [40, 50, 60, 80], name = "West Virginia Coal"}}
]
color = "Red"
x = 0
y = 6

[[hexes]]
rails = [
    {edges = [0], location = {values = [40, 50, 60, 80], name = "Pittsburgh"}}
]
color = "Red"
x = 1
y = 0

[[hexes]]
cities = [
    {value = 10, spots = 0, name = "Charleroi"},
    {value = 10, spots = 0, name = "Connellsville"}
]
x = 1
y = 1

[[hexes]]
x = 1
y = 2

[[hexes]]
x = 1
y = 3

[[hexes]]
x = 1
y = 4

[[hexes]]
terrain = "Mountain"
x = 1
y = 5

[[hexes]]
rails = [
    {edges = [4], location = {values = [40, 50, 60, 80], name = "West Virginia Coal"}}
]
color = "Red"
x = 1
y = 6

[[hexes]]
x = 2
y = 1

[[hexes]]
cities = [
    {value = 20, spots = 1, name = "Green Spring"}
]
x = 2
y = 2

[[hexes]]
x = 2
y = 3

[[hexes]]
x = 2
y = 4

[[hexes]]
x = 2
y = 5

[[hexes]]
terrain = "Mountain"
cities = [
    {value = 20, stations = ["N&W"], spots = 1, name = "Lynchburg"}
]
x = 2
y = 6

[[hexes]]
terrain = "Mountain"
private = "C&O"
cities = [
    {value = 20, spots = 1, name = "Berlin"}
]
x = 3
y = 0

[[hexes]]
terrain = "Mountain"
x = 3
y = 1

[[hexes]]
terrain = "Mountain"
x = 3
y = 2

[[hexes]]
terrain = "Mountain"
cities = [
    {value = 20, spots = 1, name = "Leesburg"}
]
x = 3
y = 3

[[hexes]]
terrain = "Mountain"
x = 3
y = 4

[[hexes]]
cities = [
    {value = 20, spots = 1, name = "Charlottesville"}
]
x = 3
y = 5

[[hexes]]
rails = [
    {edges = [1, 5]}
]
color = "Gray"
x = 4
y = 0

[[hexes]]
cities = [
    {value = 20, spots = 1, name = "Hagerstown"}
]
x = 4
y = 1

[[hexes]]
terrain = "Mountain"
x = 4
y = 2

[[hexes]]
x = 4
y = 3

[[hexes]]
x = 4
y = 4

[[hexes]]
cities = [
    {value = 10, spots = 0, name = "Fredericksburg"},
]
x = 4
y = 5

[[hexes]]
x = 4
y = 6