width = 12
height = 14

[[hexes]]
rails = [
    {edges = [5], location = {values = [40, 50, 60, 80], stations = ["P&LE"], name = "Pittsburgh"}}
]
color = "Red"
x = 0
y = 2

[[hexes]]
rails = [
    {edges = [4], location = {values = [40, 60, 80, 100], name = "Ohio"}},
    {edges = [5], location = {values = [40, 60, 80, 100], name = "Ohio"}}
]
color = "Red"
x = 0
y = 6

[[hexes]]
rails = [
    {edges = [4], location = {values = [40, 50, 60, 80], name = "West Virginia Coal"}}
]
color = "Red"
x = 0
y = 12

[[hexes]]
rails = [
    {edges = [0], location = {values = [40, 50, 60, 80], name = "Pittsburgh"}}
]
color = "Red"
x = 1
y = 1

[[hexes]]
cities = [
    {value = 0, spots = 0, name = "Charleroi"},
    {value = 0, spots = 0, name = "Connellsville"}
]
x = 1
y = 2