[[tiles]]
id = 1
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [3, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 2
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 3
rails = [
    {edges = [0, 1], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 2

[[tiles]]
id = 4
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 2

[[tiles]]
id = 7
rails = [
    {edges = [0, 1]}
]
color = "Yellow"
upgrades = []
count = -1

[[tiles]]
id = 8
rails = [
    {edges = [0, 2]}
]
color = "Yellow"
upgrades = []
count = -1

[[tiles]]
id = 9
rails = [
    {edges = [0, 3]}
]
color = "Yellow"
upgrades = []
count = -1

[[tiles]]
id = 55
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 4], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 56
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [1, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 57
rails = [
    {edges = [0, 3], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = []
count = 7

[[tiles]]
id = 58
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 2

[[tiles]]
id = 69
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = -1
rails = [
    {edges = [0, 4], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = []
count = 1