[1]
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [3, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[2]
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[3]
rails = [
    {edges = [0, 1], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 2

[4]
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 2

[7]
rails = [
    {edges = [0, 1]}
]
color = "Yellow"
count = -1

[8]
rails = [
    {edges = [0, 2]}
]
color = "Yellow"
count = -1

[9]
rails = [
    {edges = [0, 3]}
]
color = "Yellow"
count = -1

[55]
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 4], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[56]
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [1, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[57]
rails = [
    {edges = [0, 3], city = { value = 20, spots = 1 }}
]
color = "Yellow"
count = 7

[58]
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 2

[69]
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[-1]
rails = [
    {edges = [0, 4], city = { value = 20, spots = 1 }}
]
color = "Yellow"
count = 1