[[tiles]]
id = 1
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [3, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 2
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 3
rails = [
    {edges = [0, 1], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 2

[[tiles]]
id = 4
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 2

[[tiles]]
id = 7
rails = [
    {edges = [0, 1]}
]
color = "Yellow"
upgrades = [26, 27, 28, 29]
count = -1

[[tiles]]
id = 8
rails = [
    {edges = [0, 2]}
]
color = "Yellow"
upgrades = [16, 19, 23, 24, 25, 28, 29]
count = -1

[[tiles]]
id = 9
rails = [
    {edges = [0, 3]}
]
color = "Yellow"
upgrades = [19, 20, 23, 24, 26, 27]
count = -1

[[tiles]]
id = 55
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 4], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 56
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [1, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = 57
rails = [
    {edges = [0, 3], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = [14, 15]
count = 7

[[tiles]]
id = 58
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 2

[[tiles]]
id = 69
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
upgrades = []
count = 1

[[tiles]]
id = -1
rails = [
    {edges = [0, 4], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = [-2]
count = 1

[[tiles]]
id = 14
rails = [
    {edges = [0, 1, 3, 4], city = { value = 30, spots = 2 }}
]
color = "Green"
upgrades = []
count = 5

[[tiles]]
id = 15
rails = [
    {edges = [0, 1, 2, 3], city = { value = 30, spots = 2 }}
]
color = "Green"
upgrades = []
count = 6

[[tiles]]
id = 16
rails = [
    {edges = [0, 2]},
    {edges = [1, 3]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = 19
rails = [
    {edges = [0, 3]},
    {edges = [1, 5]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = 20
rails = [
    {edges = [0, 3]},
    {edges = [1, 4]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = 23
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]}
]
color = "Green"
upgrades = []
count = 3

[[tiles]]
id = 24
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]}
]
color = "Green"
upgrades = []
count = 3

[[tiles]]
id = 25
rails = [
    {edges = [0, 2]},
    {edges = [0, 4]}
]
color = "Green"
upgrades = []
count = 2

[[tiles]]
id = 26
rails = [
    {edges = [0, 3]},
    {edges = [0, 5]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = 27
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = 28
rails = [
    {edges = [0, 4]},
    {edges = [0, 5]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = 29
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = -2
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 40, spots = 2 }}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = -3
rails = [
    {edges = [0, 2], city = { value = 40, spots = 1 }},
    {edges = [3, 5], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = -4
rails = [
    {edges = [0, 1], city = { value = 40, spots = 1 }},
    {edges = [2, 3], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = []
count = 1

[[tiles]]
id = -5
rails = [
    {edges = [0, 4], city = { value = 40, spots = 1 }},
    {edges = [3, 5], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = []
count = 1