width = 12
height = 7

[[hexes]]
x = 0
y = 1
rails = [
    {edges = [5], location = {values = [40, 50, 60, 80], name = "Pittsburgh", home = "P&LE"}}
]
color = "Red"

[[hexes]]
x = 0
y = 3
rails = [
    {edges = [4], location = {values = [40, 60, 80, 100], name = "Ohio"}},
    {edges = [5], location = {values = [40, 60, 80, 100], name = "Ohio"}}
]
color = "Red"

[[hexes]]
x = 0
y = 6
rails = [
    {edges = [4], location = {values = [40, 50, 60, 80], name = "West Virginia Coal"}}
]
color = "Red"

[[hexes]]
x = 1
y = 0
rails = [
    {edges = [0], location = {values = [40, 50, 60, 80], name = "Pittsburgh"}}
]
color = "Red"

[[hexes]]
x = 1
y = 1
cities = [
    {value = 10, spots = 0, name = "Charleroi"},
    {value = 10, spots = 0, name = "Connellsville"}
]

[[hexes]]
x = 1
y = 2

[[hexes]]
x = 1
y = 3

[[hexes]]
x = 1
y = 4

[[hexes]]
x = 1
y = 5
terrain = "Mountain"

[[hexes]]
x = 1
y = 6
rails = [
    {edges = [4], location = {values = [40, 50, 60, 80], name = "West Virginia Coal"}}
]
color = "Red"

[[hexes]]
x = 2
y = 1

[[hexes]]
x = 2
y = 2
cities = [
    {value = 20, spots = 1, name = "Green Spring"}
]

[[hexes]]
x = 2
y = 3

[[hexes]]
x = 2
y = 4

[[hexes]]
x = 2
y = 5

[[hexes]]
x = 2
y = 6
terrain = "Mountain"
cities = [
    {value = 20, spots = 1, name = "Lynchburg", home = "N&W"}
]

[[hexes]]
x = 3
y = 0
terrain = "Mountain"
private = "C&O"
cities = [
    {value = 20, spots = 1, name = "Berlin"}
]

[[hexes]]
x = 3
y = 1
terrain = "Mountain"

[[hexes]]
x = 3
y = 2
terrain = "Mountain"

[[hexes]]
x = 3
y = 3
terrain = "Mountain"
cities = [
    {value = 20, spots = 1, name = "Leesburg"}
]

[[hexes]]
x = 3
y = 4
terrain = "Mountain"

[[hexes]]
x = 3
y = 5
cities = [
    {value = 20, spots = 1, name = "Charlottesville"}
]

[[hexes]]
x = 4
y = 0
rails = [
    {edges = [1, 5]}
]
color = "Gray"

[[hexes]]
x = 4
y = 1
cities = [
    {value = 20, spots = 1, name = "Hagerstown"}
]

[[hexes]]
x = 4
y = 2
terrain = "Mountain"

[[hexes]]
x = 4
y = 3

[[hexes]]
x = 4
y = 4

[[hexes]]
x = 4
y = 5
cities = [
    {value = 10, spots = 0, name = "Fredericksburg"},
]

[[hexes]]
x = 4
y = 6

[[hexes]]
x = 5
y = 0
cities = [
    {value = 20, spots = 1, name = "Harrisburg", home = "PRR"}
]

[[hexes]]
x = 5
y = 1
private = "B&S"

[[hexes]]
x = 5
y = 2

[[hexes]]
x = 5
y = 3
cities = [
    {value = 30, spots = 1, name= "Washington DC"}
]

[[hexes]]
x = 5
y = 4
terrain = "River"

[[hexes]]
x = 5
y = 5

[[hexes]]
x = 5
y = 6
rails = [
    {edges = [3, 4]}
]
color = "Gray"

[[hexes]]
x = 6
y = 0
rails = [
    {edges = [0, 1]},
    {edges = [1, 5]}
]
color = "Gray"

[[hexes]]
x = 6
y = 1
terrain = "River"
cities = [
    {value = 10, spots = 0, name = "Columbia"}
]

[[hexes]]
x = 6
y = 2
private = "B&S"

[[hexes]]
x = 6
y = 3

[[hexes]]
x = 6
y = 4
terrain = "River"

[[hexes]]
x = 6
y = 5
terrain = "River"

[[hexes]]
x = 6
y = 6
cities = [
    {value = 20, spots = 1, name = "Richmond", home = "C&O"}
]

[[hexes]]
x = 7
y = 0
private = "C-P"

[[hexes]]
x = 7
y = 1
terrain = "River"
cities = [
    {value = 20, spots = 1, name = "Strasburg", home = "SRR"}
]

[[hexes]]
x = 7
y = 2
terrain = "River"
rails = [
    {edges = [1], city = { value = 30, spots = 1, name = "Baltimore", home = "B&O"}},
    {edges = [4], city = { value = 30, spots = 1, name = "Baltimore"}}
]
color = "Yellow"
upgrades = [-3, -4, -5]

[[hexes]]
x = 7
y = 5
terrain = "River"

[[hexes]]
x = 7
y = 6
rails = [
    {edges = [2], location = {values = [30, 40, 50, 60], name = "Norfolk"}}
]
color = "Red"

[[hexes]]
x = 8
y = 1
private = "C-P"

[[hexes]]
x = 8
y = 2
terrain = "River"
cities = [
    {value = 10, spots = 0, name = "Wilmington"}
]

[[hexes]]
x = 8
y = 3

[[hexes]]
x = 8
y = 4
rails = [
    {edges = [3, 5], city = {value = 30, spots = 0, name = "Delmarva Peninsula"}}
]
color = "Gray"

[[hexes]]
x = 9
y = 0
cities = [
    {value = 20, spots = 1, name = "Allentown", home = "LV"}
]

[[hexes]]
x = 9
y = 1
rails = [
    {edges = [0], city = { value = 30, spots = 1, name = "Philadelphia"}},
    {edges = [3], city = { value = 30, spots = 1, name = "Philadelphia"}}
]
color = "Yellow"
upgrades = [-3, -4, -5]

[[hexes]]
x = 9
y = 2
terrain = "River"
cities = [
    {value = 20, spots = 1, name = "Camden", home = "C&A"}
]

[[hexes]]
x = 9
y = 3

[[hexes]]
x = 9
y = 4

[[hexes]]
x = 10
y = 0
rails = [
    {edges = [0, 1], city = {value = 30, spots = 0, name = "Easton"}}
]
color = "Gray"

[[hexes]]
x = 10
y = 1
private = "D&R"
cities = [
    {value = 10, spots = 0, name = "Trenton"},
    {value = 10, spots = 0, name = "Amboy"}
]

[[hexes]]
x = 10
y = 2
cities = [
    {value = 10, spots = 0, name = "Princeton"},
    {value = 10, spots = 0, name = "Burlington"}
]

[[hexes]]
x = 10
y = 3
rails = [
    {edges = [2, 3]}
]
color = "Gray"

[[hexes]]
x = 11
y = 0
rails = [
    {edges = [0], location = {values = [40, 60, 80, 100], name = "New York"}},
    {edges = [1], location = {values = [40, 60, 80, 100], name = "New York"}}
]
color = "Red"

[[hexes]]
x = 11
y = 1