[[tiles]]
id = 1
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [3, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[[tiles]]
id = 2
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[[tiles]]
id = 3
rails = [
    {edges = [0, 1], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 2

[[tiles]]
id = 4
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 2

[[tiles]]
id = 7
rails = [
    {edges = [0, 1]}
]
color = "Yellow"
upgrades = [26, 27, 28, 29]
count = -1

[[tiles]]
id = 8
rails = [
    {edges = [0, 2]}
]
color = "Yellow"
upgrades = [16, 19, 23, 24, 25, 28, 29]
count = -1

[[tiles]]
id = 9
rails = [
    {edges = [0, 3]}
]
color = "Yellow"
upgrades = [19, 20, 23, 24, 26, 27]
count = -1

[[tiles]]
id = 55
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 4], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[[tiles]]
id = 56
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [1, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[[tiles]]
id = 57
rails = [
    {edges = [0, 3], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = [14, 15]
count = 7

[[tiles]]
id = 58
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 2

[[tiles]]
id = 69
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"
count = 1

[[tiles]]
id = -1
rails = [
    {edges = [0, 4], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = [-2]
count = 1

[[tiles]]
id = 14
rails = [
    {edges = [0, 1, 3, 4], city = { value = 30, spots = 2 }}
]
color = "Green"
upgrades = [611]
count = 5

[[tiles]]
id = 15
rails = [
    {edges = [0, 1, 2, 3], city = { value = 30, spots = 2 }}
]
color = "Green"
upgrades = [611]
count = 6

[[tiles]]
id = 16
rails = [
    {edges = [0, 2]},
    {edges = [1, 3]}
]
color = "Green"
upgrades = [43, 70]
count = 1

[[tiles]]
id = 19
rails = [
    {edges = [0, 3]},
    {edges = [1, 5]}
]
color = "Green"
upgrades = [45, 46]
count = 1

[[tiles]]
id = 20
rails = [
    {edges = [0, 3]},
    {edges = [1, 4]}
]
color = "Green"
upgrades = [44, 47]
count = 1

[[tiles]]
id = 23
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]}
]
color = "Green"
upgrades = [41, 43, 45, 47]
count = 3

[[tiles]]
id = 24
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]}
]
color = "Green"
upgrades = [42, 43, 46, 47]
count = 3

[[tiles]]
id = 25
rails = [
    {edges = [0, 2]},
    {edges = [0, 4]}
]
color = "Green"
upgrades = [40, 45, 46]
count = 2

[[tiles]]
id = 26
rails = [
    {edges = [0, 3]},
    {edges = [0, 5]}
]
color = "Green"
upgrades = [42, 44, 45]
count = 1

[[tiles]]
id = 27
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]}
]
color = "Green"
upgrades = [41, 4, 46]
count = 1

[[tiles]]
id = 28
rails = [
    {edges = [0, 4]},
    {edges = [0, 5]}
]
color = "Green"
upgrades = [39, 43, 46, 70]
count = 1

[[tiles]]
id = 29
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]}
]
color = "Green"
upgrades = [39, 43, 45, 70]
count = 1

[[tiles]]
id = -2
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 40, spots = 2 }}
]
color = "Green"
upgrades = [-6]
count = 1

[[tiles]]
id = -3
rails = [
    {edges = [0, 2], city = { value = 40, spots = 1 }},
    {edges = [3, 5], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = [-7]
count = 1

[[tiles]]
id = -4
rails = [
    {edges = [0, 1], city = { value = 40, spots = 1 }},
    {edges = [2, 3], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = [-7]
count = 1

[[tiles]]
id = -5
rails = [
    {edges = [0, 4], city = { value = 40, spots = 1 }},
    {edges = [3, 5], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = [-7]
count = 1

[[tiles]]
id = 39
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]},
    {edges = [1, 2]}
]
color = "Brown"
count = 1

[[tiles]]
id = 40
rails = [
    {edges = [0, 2]},
    {edges = [0, 4]},
    {edges = [2, 4]}
]
color = "Brown"
count = 1

[[tiles]]
id = 41
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]},
    {edges = [3, 4]}
]
color = "Brown"
count = 1

[[tiles]]
id = 42
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]},
    {edges = [2, 3]}
]
color = "Brown"
count = 1

[[tiles]]
id = 43
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]},
    {edges = [1, 2]},
    {edges = [1, 3]},
]
color = "Brown"
count = 2

[[tiles]]
id = 44
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]},
    {edges = [1, 4]},
    {edges = [3, 4]},
]
color = "Brown"
count = 1

[[tiles]]
id = 45
rails = [
    {edges = [0, 3]},
    {edges = [0, 5]},
    {edges = [1, 3]},
    {edges = [1, 5]},
]
color = "Brown"
count = 1

[[tiles]]
id = 46
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]},
    {edges = [1, 5]},
    {edges = [3, 5]},
]
color = "Brown"
count = 1

[[tiles]]
id = 47
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]},
    {edges = [1, 3]},
    {edges = [1, 4]},
]
color = "Brown"
count = 2

[[tiles]]
id = 70
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]},
    {edges = [1, 3]},
    {edges = [2, 3]},
]
color = "Brown"
count = 1

[[tiles]]
id = 611
rails = [
    {edges = [0, 1, 2, 3, 4], city = { value = 40, spots = 2 }}
]
color = "Brown"
upgrades = [915]
count = 5

[[tiles]]
id = -6
rails = [
    {edges = [0, 1, 2, 3, 4, 5], city = { value = 70, spots = 3 }}
]
color = "Brown"
upgrades = [-8]
count = 1

[[tiles]]
id = -7
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 50, spots = 2 }}
]
color = "Brown"
upgrades = [-9]
count = 2

[[tiles]]
id = 915
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 50, spots = 3 }}
]
color = "Gray"
count = 5

[[tiles]]
id = -8
rails = [
    {edges = [0, 1, 2, 3, 4, 5], city = { value = 100, spots = 4 }}
]
color = "Gray"
count = 1

[[tiles]]
id = -9
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 70, spots = 3 }}
]
color = "Gray"
count = 2