[[tiles]]
id = 1
count = 1
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [3, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 2
count = 1
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 3
count = 2
rails = [
    {edges = [0, 1], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 4
count = 2
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 7
count = -1
rails = [
    {edges = [0, 1]}
]
color = "Yellow"
upgrades = [26, 27, 28, 29]

[[tiles]]
id = 8
count = -1
rails = [
    {edges = [0, 2]}
]
color = "Yellow"
upgrades = [16, 19, 23, 24, 25, 28, 29]

[[tiles]]
id = 9
count = -1
rails = [
    {edges = [0, 3]}
]
color = "Yellow"
upgrades = [19, 20, 23, 24, 26, 27]

[[tiles]]
id = 55
count = 1
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 4], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 56
count = 1
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }},
    {edges = [1, 3], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 57
count = 7
rails = [
    {edges = [0, 3], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = [14, 15]

[[tiles]]
id = 58
count = 2
rails = [
    {edges = [0, 2], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = 69
count = 1
rails = [
    {edges = [0, 3], city = { value = 10, spots = 0 }},
    {edges = [1, 5], city = { value = 10, spots = 0 }}
]
color = "Yellow"

[[tiles]]
id = -1
count = 1
rails = [
    {edges = [0, 4], city = { value = 20, spots = 1 }}
]
color = "Yellow"
upgrades = [-2]

[[tiles]]
id = 14
count = 5
rails = [
    {edges = [0, 1, 3, 4], city = { value = 30, spots = 2 }}
]
color = "Green"
upgrades = [611]

[[tiles]]
id = 15
count = 6
rails = [
    {edges = [0, 1, 2, 3], city = { value = 30, spots = 2 }}
]
color = "Green"
upgrades = [611]

[[tiles]]
id = 16
count = 1
rails = [
    {edges = [0, 2]},
    {edges = [1, 3]}
]
color = "Green"
upgrades = [43, 70]

[[tiles]]
id = 19
count = 1
rails = [
    {edges = [0, 3]},
    {edges = [1, 5]}
]
color = "Green"
upgrades = [45, 46]

[[tiles]]
id = 20
count = 1
rails = [
    {edges = [0, 3]},
    {edges = [1, 4]}
]
color = "Green"
upgrades = [44, 47]

[[tiles]]
id = 23
count = 3
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]}
]
color = "Green"
upgrades = [41, 43, 45, 47]

[[tiles]]
id = 24
count = 3
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]}
]
color = "Green"
upgrades = [42, 43, 46, 47]

[[tiles]]
id = 25
count = 2
rails = [
    {edges = [0, 2]},
    {edges = [0, 4]}
]
color = "Green"
upgrades = [40, 45, 46]

[[tiles]]
id = 26
count = 1
rails = [
    {edges = [0, 3]},
    {edges = [0, 5]}
]
color = "Green"
upgrades = [42, 44, 45]

[[tiles]]
id = 27
count = 1
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]}
]
color = "Green"
upgrades = [41, 4, 46]

[[tiles]]
id = 28
count = 1
rails = [
    {edges = [0, 4]},
    {edges = [0, 5]}
]
color = "Green"
upgrades = [39, 43, 46, 70]

[[tiles]]
id = 29
count = 1
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]}
]
color = "Green"
upgrades = [39, 43, 45, 70]

[[tiles]]
id = -2
count = 1
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 40, spots = 2 }}
]
color = "Green"
upgrades = [-6]

[[tiles]]
id = -3
count = 1
rails = [
    {edges = [0, 2], city = { value = 40, spots = 1 }},
    {edges = [3, 5], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = [-7]

[[tiles]]
id = -4
count = 1
rails = [
    {edges = [0, 1], city = { value = 40, spots = 1 }},
    {edges = [2, 3], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = [-7]

[[tiles]]
id = -5
count = 1
rails = [
    {edges = [0, 4], city = { value = 40, spots = 1 }},
    {edges = [3, 5], city = { value = 40, spots = 1 }}
]
color = "Green"
upgrades = [-7]

[[tiles]]
id = 39
count = 1
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]},
    {edges = [1, 2]}
]
color = "Brown"

[[tiles]]
id = 40
count = 1
rails = [
    {edges = [0, 2]},
    {edges = [0, 4]},
    {edges = [2, 4]}
]
color = "Brown"

[[tiles]]
id = 41
count = 1
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]},
    {edges = [3, 4]}
]
color = "Brown"

[[tiles]]
id = 42
count = 1
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]},
    {edges = [2, 3]}
]
color = "Brown"

[[tiles]]
id = 43
count = 2
rails = [
    {edges = [0, 2]},
    {edges = [0, 3]},
    {edges = [1, 2]},
    {edges = [1, 3]},
]
color = "Brown"

[[tiles]]
id = 44
count = 1
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]},
    {edges = [1, 4]},
    {edges = [3, 4]},
]
color = "Brown"

[[tiles]]
id = 45
count = 1
rails = [
    {edges = [0, 3]},
    {edges = [0, 5]},
    {edges = [1, 3]},
    {edges = [1, 5]},
]
color = "Brown"

[[tiles]]
id = 46
count = 1
rails = [
    {edges = [0, 1]},
    {edges = [0, 3]},
    {edges = [1, 5]},
    {edges = [3, 5]},
]
color = "Brown"

[[tiles]]
id = 47
count = 2
rails = [
    {edges = [0, 3]},
    {edges = [0, 4]},
    {edges = [1, 3]},
    {edges = [1, 4]},
]
color = "Brown"

[[tiles]]
id = 70
count = 1
rails = [
    {edges = [0, 1]},
    {edges = [0, 2]},
    {edges = [1, 3]},
    {edges = [2, 3]},
]
color = "Brown"

[[tiles]]
id = 611
count = 5
rails = [
    {edges = [0, 1, 2, 3, 4], city = { value = 40, spots = 2 }}
]
color = "Brown"
upgrades = [915]

[[tiles]]
id = -6
count = 1
rails = [
    {edges = [0, 1, 2, 3, 4, 5], city = { value = 70, spots = 3 }}
]
color = "Brown"
upgrades = [-8]

[[tiles]]
id = -7
count = 2
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 50, spots = 2 }}
]
color = "Brown"
upgrades = [-9]

[[tiles]]
id = 915
count = 5
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 50, spots = 3 }}
]
color = "Gray"

[[tiles]]
id = -8
count = 1
rails = [
    {edges = [0, 1, 2, 3, 4, 5], city = { value = 100, spots = 4 }}
]
color = "Gray"

[[tiles]]
id = -9
count = 2
rails = [
    {edges = [0, 1, 2, 4, 5], city = { value = 70, spots = 3 }}
]
color = "Gray"